"""new model update

Revision ID: 302edaa16b3b
Revises: 98ffa020bb25
Create Date: 2025-12-29 18:57:35.194341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302edaa16b3b'
down_revision = '98ffa020bb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion_flier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion_flier', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
