"""added create_at

Revision ID: 695066085614
Revises: f001fd17331f
Create Date: 2026-01-12 16:57:24.442873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695066085614'
down_revision = 'f001fd17331f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
