"""newsletter

Revision ID: 773b51435f42
Revises: a1ca38586452
Create Date: 2025-06-23 13:48:35.516245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773b51435f42'
down_revision = 'a1ca38586452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
