"""added password hashes to the user update

Revision ID: 7d212d418db0
Revises: c80d1ffcf28d
Create Date: 2025-06-25 05:43:37.267662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d212d418db0'
down_revision = 'c80d1ffcf28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
