"""added a model field

Revision ID: 803bdf6b2e53
Revises: 9392e726da8a
Create Date: 2025-12-10 09:05:33.386665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803bdf6b2e53'
down_revision = '9392e726da8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
